name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'tpf-frontend/**' # Cambios en frontend
      - 'tpf-backend/**'  # Cambios en backend

jobs:
  tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar dependencias y ejecutar pruebas
      - name: Install Dependencies and Run Tests
        working-directory: ./tpf-backend
        run: |
          npm install
          npm test

  build-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    needs: tests
    if: contains(github.event.commits.*.modified, 'tpf-frontend/') || contains(github.event.head_commit.message, 'frontend')

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir imagen del frontend
    - name: Build Frontend Docker Image
      working-directory: ./tpf-frontend
      run: |
        docker build -t cristian241/frontend-app:${{ github.sha }} .
        docker tag cristian241/frontend-app:${{ github.sha }} cristian241/frontend-app:latest

    # 4. Subir imagen del frontend a Docker Hub
    - name: Push Frontend Docker Image
      run: |
        docker push cristian241/frontend-app:${{ github.sha }}
        docker push cristian241/frontend-app:latest

  build-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    needs: tests
    if: contains(github.event.commits.*.modified, 'tpf-backend/') || contains(github.event.head_commit.message, 'backend')

    steps:
    # 1. Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir imagen del backend
    - name: Build Backend Docker Image
      working-directory: ./tpf-backend
      run: |
        docker build -t cristian241/backend-app:${{ github.sha }} .
        docker tag cristian241/backend-app:${{ github.sha }} cristian241/backend-app:latest

    # 4. Subir imagen del backend a Docker Hub
    - name: Push Backend Docker Image
      run: |
        docker push cristian241/backend-app:${{ github.sha }}
        docker push cristian241/backend-app:latest

    # 4. Subir imagen del backend a Docker Hub
    - name: Push Backend Docker Image
      run: |
        docker push cristian241/backend-app:${{ github.sha }}
        docker push cristian241/backend-app:latest
